### ISSUE TITLE
Which would be the best way to do an async database call when using DroidMVP?

### ISSUE THREAD

**Issue by cristian-calugar** [andrzejchm/DroidMVP#10]
Hi Andrzej,

We would like to use DroidMVP library in our project. From the MVP examples that we have researched, this one seems to be the most clear, easy to understand and adapt to our project.

What we would like to know is what do you believe that would be the best way to implement an async database call from a presenter. Would you be kind to add such an example in the sample app?

Thanks in advance,
Cristi.

**Comment by andrzejchm** [comment]
It's a bit out of scope of this library, but my solution would be to create `*Usecase` (or if you preffer: `*Interactor` class that would encapsulate specific usecase of the business logic (for example retrieving User details) and which would then be executed from within presenter either by a some sort of `UsecaseExecutor` which deals with delegating work to background thread and reporting back the results to main thread or to simply use RxJava with correct schedulers.

 a small example: https://gist.github.com/andrzejchm/b78bb7412d31078e4d8e9841401914a9

**Comment by cristian-calugar** [comment]
Thank you Andrzej! 
Just wanted to know your opinion. We were also looking at similar solutions with and Interactor or Rx.
