### ISSUE TITLE
Presentation Model may not be saved?

### ISSUE THREAD

**Issue by belinwu** [andrzejchm/DroidMVP#15]
If `onSaveInstanceState()` called before remote api callback, Presentation Model may not be saved?

**Comment by andrzejchm** [comment]
it might depend on exact Android implementation, but if your model is stored as `Parcelable` there is a good chance system will not persist it until it really needs, even though it called `onSaveInstanceState`. It might just hold the reference until it is really needed and the memory is low. But I would not make any assumptions on that and would suggest to either cancel api call in `detachView` or `onDestroy`, or check whether the model contains the data that came from API callback on each `attachView`. (Assuming you saved this data into the model after in the callback)
